image: node:20-slim

stages:
  - test
  - min-coverage

variables:
  MIN_COVERAGE: 70  # set the threshold at 80%

jest_test:
  stage: test
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm run test
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  only:
    - merge_requests
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
  after_script:
    - # do something with the coverage report
